# Generated by Django 5.2 on 2025-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_whatsapp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='whatsapp_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
